[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["workflowextern_nq"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "workflowextern_nq"
  org = "malithiinternproject"
  version = "3.1.0"

