[camundaconfig]
CAMUNDA_ENGINE_URL = "https://8c34-2402-d000-a400-1510-65fd-dc97-ef93-6dab.in.ngrok.io/engine-rest/process-definition"

DEFINITION_IDS = [ { evenetType = "User Add", ID ="Useradd:1:3ff03477-c970-11ed-9db5-9e29762f7844"}, 
          { evenetType = "Role Add", ID ="Useradd:1:3ff03477-c970-11ed-9db5-9e29762f7844"},
          { evenetType = "User Update", ID ="Useradd:1:3ff03477-c970-11ed-9db5-9e29762f7844"}
           ]


[bpelconfig]
USER_CREDENTIALS = "admin:admin"
BASIC_AUTH_TYPE = "Basic"
BPEL_ENGINE_URL = "http://localhost:9763/api/server/v1/workflow/"
WORKFLOW_URL = "/services/create_RoleService"

[bpmnConfig]
USER_CREDENTIALS = "admin:admin"
BASIC_AUTH_TYPE = "Basic"
BPMN_ENGINE_URL = "http://localhost:9763/api/server/v1/workflow/"


[callbackconfig]
CALLBACK_END_POINT = "https://455d-2402-d000-a400-6179-f4b7-ab4b-fc4e-652d.in.ngrok.io/api/server/v1/workflow/"


