[camundaconfig]
CAMUNDA_ENGINE_URL = "https://0bfb-2402-d000-a400-a3a3-9155-9505-2eaa-cf27.in.ngrok.io/engine-rest/process-definition"

[[camundaWorkflowConfigs]]
workflowID= "5896610a-4039-4c09-a843-c3027cf8272e"
processDefinitionID="Useradd:2:343e0712-d1d6-11ed-88bc-9e29762f7844"

[[camundaWorkflowConfigs]]
workflowID= "5896610a-4039-4c09-a843-c3027cf8272euu"
processDefinitionID="Useradd:1:3ff03477-c970-11ed-9db5-9e29762f7844"


[bpelconfig]
USER_CREDENTIALS = "admin:admin"
BASIC_AUTH_TYPE = "Basic"
BPEL_ENGINE_URL = "http://localhost:9763/api/server/v1/workflow/"
WORKFLOW_URL = "/services/create_RoleService"

[bpmnConfig]
USER_CREDENTIALS = "admin:admin"
BASIC_AUTH_TYPE = "Basic"
BPMN_ENGINE_URL = "http://localhost:9763/api/server/v1/workflow/"


[callbackconfig]
CALLBACK_END_POINT = "https://455d-2402-d000-a400-6179-f4b7-ab4b-fc4e-652d.in.ngrok.io/api/server/v1/workflow/"


